# Generated by Django 4.1.7 on 2023-05-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogosphere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile-image'),
        ),
    ]
